# dic1={1:10,2:20}
# dic2={3:30,2:40}
# dic3={5:50,6:60}
# a={}
# for i in (dic1,dic2,dic3):
#     # print(i)
#     a.update(i)
# print(a)
    
d1={1:10,2:20}
d2={3:30,2:40}
d3={5:50,6:60}
# for i in d2:
#     if i in d1:
#         d1[i]=d1[i]+d2[i]
#         d1.update(d3)
#     else:
#         d1[i]=d2[i]
# print(d1)




# x = 75
# def myfunc():
#     return x 
#     # print(x)

# myfunc()
# # print(x)





# print(bool(0), bool(3.14159), bool(-3), bool(1.0+1j))

# x = 50
# def fun1():
#      global x 
#      x = 20
# fun1()
# print(x) 

# x = 75
# def myfunc():
#     # x=x+1
# #     # X=X+1
#     print(x)

# myfunc()
# print(x)

# # output error


# str1 = 'Ault\\'Kelly'


# str1 = 'Ault\\'Kelly'
# str1 = 'Ault\'Kelly'
# str1 = """Ault'Kelly"""

# aTuple = (1, 'Jhon', 1+3j)
# print(type(aTuple[2:3]))
# output


# x = 50
# def fun1():
#     x = 25
#     print(x)
    
# fun1()
# print(x)
# outpout=25,50

# def func1():
#     x = 50
#     return x
# func1()
# print(x)
# outpout=name error


# aTuple = (1, 'Jhon', 1+3j)
# print(type(aTuple[2:3]))

# print(type(10))


# x = 50
# def fun1():
#     global x
#     x = 20
# fun1()
# print(x) # it should print 20

# x = 10
# y = 50
# if x ** 2 > 100 and y < 100:
#     print(x, y)



# today queues

# for num in range(-2,-5,-1):
#     print(num, end=", ")




# x = 0
# a = 0
# b = -5
# if a > 0:
#     if b < 0: 
#         x = x + 5 
#     elif a > 5:
#         x = x + 4
#     else:
#         x = x + 3
# else:
#     x = x + 2
# print(x)

# numbers = [10, 20]
# items = ["Chair", "Table"]

# for x in numbers:
#   for y in items:
#     print(x, y)
# o/p=10chair
#     10table
#     20chair
#     20table



# a,b = 12, 5
# if a + b:
#     print('True')
# else:
#   print('False')
# o/p=true

# if -3 will evaluate to True
# o/p=true

# x = 0
# a = 5
# b = 5
# if a > 0:
#     if b < 0: 
#         x = x + 5 
#     elif a > 5:
#         x = x + 4
#     else:
#         x = x + 3
# else:
#     x = x + 2
# print(x)
# o/p=3

# for num in range(10, 14):
#        for i in range(2, num):
#             if num%i == 1:
#                 print(num)
#             break
# o/p=11
#     13


# for l in 'Jhon':
#    if l == 'o':
#       pass
#    print(l, end=", ")
# o/p=j,h,o,n

# var = 10
# for i in range(10):
#     for j in range(2, 10, 1):
#         if var % 2 == 0:
#             continue
#             var += 1
#     var+=1
# else:
#     var+=1
# print(var)
# o/p=21

# x = 0
# for i in range(10):
#   for j in range(-1, -10, -1):
#     x += 1
#     print(x)
# o/p=87,88,89,90

# for num in range(2,-5,-1):
#     print(num, end=", ")
# o/p=2,1,-1,-2,-3,-4

# f = open("test.txt", "r")
# print(f.readline(3))
# f.close()
# o/p=error

# print('[%c]' % 65)
# o/p=[A]



# print('%d %d %.2f' % (11, '22', 11.22))
# o/p=type error

# print('PYnative ', end='//')
# print(' is for ', end='//')
# print(' Python Lovers', end='//')


# print(sep='--', 'Ben', 25, 'California')
# syntax error

# print('%x, %X' % (15, 15))
# o/p=f,F

# x = float('NaN')
# print('%f, %e, %F, %E' % (x, x, x, x))

# f = open("test.txt", "r")
# print(f.readline(3))
# f.close()
# aaa

# var = "James" * 2  * 3
# print(var)

# for x in range(0.5, 5.5, 0.5):
#   print(x)

# def calculate (num1, num2=4):
#      res = num1 * num2
#   print(res)

# calculate(5, 6)

# for i in range(10, 15, 1):
#   print( i, end=', ')

# listOne = [20, 40, 60, 80]
# listTwo = [20, 40, 60, 80]

# print(listOne == listTwo)
# print(listOne is listTwo)

# salary = 8000

# def printSalary():
#   salary = 12000
#   print("Salary:", salary)
  
# printSalary()
# print("Salary:", salary)
# o/p=12000
#     800

# var= "James Bond"
# print(var[1::-1]) 
# for x in range(2,2,15):
#   print(x)
# salary = 8000

# def printSalary():
#   salary = 12000
#   print("Salary:", salary)
  
# printSalary()
# print("Salary:", salary)
# print('%d %s %.2f' % (11, '22', 11.22))

# a="sakshi gangwar"
# b="s.g sakshi gangwar" 
# c=


# n=input("enter the number::")
# sub=["hindi","english","math","science"]
# marks=["23","45","67","89"]
# i=0
# while i<len(sub):
#       if n==sub[i]:
#             print(marks[i])
#       i=i+1


a=["a","b","v","y"]
b=["w","e","q","z"]



